name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual runs from the Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: Build and run tests (Maven)
        run: mvn -B -DskipTests=false package

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app-jar
          path: target/*.jar
